### ISSUE TITLE
Move radeco and rune repositories into another namespace

### ISSUE THREAD

**Issue by XVilka** [radareorg/radeco-lib#107]
Because the project indends to be quite big and Rust encourage splitting projects into a small crates, it makes sense not to clobber "radare/" namespace, but make a dedicated one for that.

 - [x] https://github.com/radare/radeco-lib
 - [x] https://github.com/radare/rune
 - [x] https://github.com/radare/esil-rs
 - [x] https://github.com/radare/arch-rs
 - [x] https://github.com/radare/ir-rs
 - [x] https://github.com/radare/rune
 - [x] https://github.com/radare/r2pipe.rs
 - [x] https://github.com/radare/radare2-rust

@radareorg your thoughts?

**Comment by XVilka** [comment]
err, I meant @radare

**Comment by sushant94** [comment]
+1 for this. I suggest we have something like `radare-rs/` org/namespace (or any variation of that, `radareorg-rs/` etc.)

**Comment by chinmaydd** [comment]
Yep, +1 for this.

**Comment by ZhangZhuoSJTU** [comment]
Cannot agree more ;P

**Comment by chinmaydd** [comment]
Should we move ahead on this XVilka? I think now would be a good time to do it, before we get back to dev.

**Comment by XVilka** [comment]
Only @radare can do that. Can you @radare please create a new namespace, I don't know what is the best name, radare-rs? And transfer new projects into it. Or we can move everything in radareorg:
 - [ ] https://github.com/radare/radeco-lib
 - [ ] https://github.com/radare/rune
 - [ ] https://github.com/radare/esil-rs
 - [ ] https://github.com/radare/arch-rs
 - [ ] https://github.com/radare/rune
 - [ ] https://github.com/radare/r2pipe.rs
 - [ ] https://github.com/radare/radare2-rust

Did I forgot something?

**Comment by chinmaydd** [comment]
Even https://github.com/radare/ir-rs was created and I think we should move that as well.

**Comment by sushant94** [comment]
+1 for radare-rs/ org

**Comment by radare** [comment]
done
