### ISSUE TITLE
Minidec should use latest improvements from radeco-lib

### ISSUE THREAD

**Issue by sushant94** [radareorg/radeco-lib#119]
Minidec currently uses the old deprecated containers. This should be ported to use the latest container systems.

Additionally, we should also look into adding more command line options to select analysis run in minidec as radeco is not actively developed.

**Comment by kriw** [comment]
Currently, I'm working on this issue, and have two question.
These two questions are about src/analysis/interproc/fixcall.rs.

1, What should `bind.mark_preserved()` be replaced with?
It seems there is no alternative function.
https://github.com/kriw/radeco-lib/commit/90135ce7bcb61d1087c0cdde08b6427b77558255#diff-5c08fc240978b9c76be181eb6798a545R293

2. What is `call_site` ?
It seems we can get 'cgid' and retrieve callers and callees by the `cgid` and CallGraph. Is it related to `call_site`?
https://github.com/kriw/radeco-lib/commit/90135ce7bcb61d1087c0cdde08b6427b77558255#diff-5c08fc240978b9c76be181eb6798a545R205

**Comment by sushant94** [comment]
* I would suggest fixing `src/analysis/interproc/fixcall.rs` in another issue. For that, you would need to extend the current bindings struct to include preserved/modified/etc. flags, and then implement the  above on top of that.

* The call-graph is currently implemented as a graph, where the nodes are  function start addresses. An edge from `A -> B` indicates A calls B and  the edge data contains the actual call-site information (which includes location of the call, and the caller-callee context binding).

**Comment by XVilka** [comment]
@kriw @sushant94 what is the current state of this one?

**Comment by kriw** [comment]
Almost done. Currently minidec use the latest containers, but src/analysis/valueset/analyzer_wysinwyx.rs still use duplicated containers.
