### ISSUE TITLE
Constant propagation appears to be bugged

### ISSUE THREAD

**Issue by HMPerson1** [radareorg/radeco-lib#141]
running constprop on `sym.main` in `ex-bins/simple2`
before: [sym.main_PRE.txt](https://github.com/radare/radeco-lib/files/1993848/sym.main_PRE.txt)
after: [sym.main_POST.txt](https://github.com/radare/radeco-lib/files/1993850/sym.main_POST.txt) -- a block that had two successors now has none

**Comment by XVilka** [comment]
Did you look into after?

**Comment by HMPerson1** [comment]
I have not.
