### ISSUE TITLE
Some analysis prevent recovering local variables

### ISSUE THREAD

**Issue by kriw** [radareorg/radeco-lib#174]
`RadecoFunction` have `HashMap<NodeIndex, VarBindng>` for recovring locals, but some analysis modify NodeIndex of `RadecoFunctions`'s SSA such as `inst_combine`.  We need to avoid the modification or fix the hash map after modification.

These are the possible solutions which comes to my mind.
- Fix the binding automatically
- Fix the hash map key (NodeIndex) automatically
- Recover bindings after analyses 

### Fix the binding automatically
Fixing the binding means modifying `VarBinding::btype` if it is `RegisterLocal` in each analyses (e.g., `inst_combine` modify `rbp - 0x10` to `rsp - 0x8`, so some bindings should replace `rbp` with `rsp` and subtract 8 from its offset.)

### Fix the hash map key (NodeIndex) automatically
After each analysis, this idea replaces the corresponding NodeIndex of the hash map. This idea does not modify VarBinding at all.

### Recover bindings after analyses
Recovering bindings after analyses which modify nodes are done.

**Comment by HMPerson1** [comment]
`inst_combine` (and most other passes I think) use `SSAStorage::replace_value`, so another approach could be to create dummy nodes in the SSA with edges connecting to the actual value node and then keep only the dummy nodes in the hash map. When the actual value nodes get replaced, `replace_value` will automatically update the edges, and the dummy nodes will still "point" to the correct value node with no additional effort. This does however add a bit of complexity to any code trying to access the value of the bindings.

**Comment by XVilka** [comment]
Do you think  it can be done before 0.1 release?

**Comment by kriw** [comment]
I think this can be done this week.
