### ISSUE TITLE
Memory error at analysis::arithmetic

### ISSUE THREAD

**Issue by kriw** [radareorg/radeco-lib#254]
I tried [ioli/crackme0x00](https://github.com/radare/radare2-regressions/blob/master/bins/elf/ioli/crackme0x00).
The process stopped with the follwing error.
`memory allocation of 1326004114 bytes failedzsh: abort (core dumped)  cargo run`

It seems this error happend at `gmatch::grep`.

**Comment by Mm7** [comment]
I saw this exact problem with another binary, but It disappeared after updating radare. Did you try to update it first?

**Comment by Mm7** [comment]
@kriw  Hi, please can you check #255 ? It fixed the issue here. Thank you!
