### ISSUE TITLE
Rust package restructuring

### ISSUE THREAD

**Issue by jrozner** [radareorg/radeco-lib#293]
This is a proposal to restructure the radeco related rust based code and merge the related crates into a single repository that utilizes a Cargo workspace. It would include the following crates:
- [x] radeco
- [x] radeco-lib
- [x] esil-rs
- [x] arch-rs
- [ ] radeco-regressions
- [x] rune

Depending on future development of rust based components with respect to r2 in general this could become the central point for others as well or kept strictly to radeco related code depending on the amount of overlap.

## Justification

1. This is a fairly common pattern within the Rust ecosystem where multiple crates are part of a project and dependent on each other.
2. It aids with versioning code together within development. Instead of having to pin versions in Cargo to master or a specific commit if a change is made in one crate all are kept in lock step so it reduces the risk of broken builds as one part changes
3. It allows RLS to provide more help such as it's integration for jumping to definitions and looking up code
4. Less overhead of managing individual repos and keeping them up to date as development is performed on various parts

## Process

Create a new repository or choose one to be the main one and use git subtree to migrate the git histories of each current repo into the new one that is going to be the primary repo. This will retain all history from all crates within the new one. Lastly, update crates and create the top level workspace for Cargo.

**Comment by XVilka** [comment]
So it is done now.
