### ISSUE TITLE
Enable Doc, Travis CI and Appveyor on radeco

### ISSUE THREAD

**Issue by Maijin** [radareorg/radeco-lib#3]
- [x] Configure Appveyor @xvilka
- [x] Add radeco to r2pm
- [x] Enable Appveyor on github @radare 
- [x] Add the .travis.yml file
- [x] Enable the Travis project on github + travis website @radare
- [x] Add the "build passing" logos on the README
- [x] Add makefile or/and build instructions for humans(tm)
- [x] Automate the rust doc generation @sushant94 
- [x] Coverall.io #18

**Comment by Maijin** [comment]
This issue to be assigned to @XVilka

**Comment by XVilka** [comment]
Project on AppVeyor created: https://ci.appveyor.com/project/radare/radeco-lib

**Comment by XVilka** [comment]
@radare can you please add AppVeyor webhook in this project? For both commits and pull requests?

**Comment by chinmaydd** [comment]
radeco is now available in r2pm. Looks like all of the above are now solved.
