### ISSUE TITLE
Reimplementation of some analysis in Rust

### ISSUE THREAD

**Issue by radare** [radareorg/radeco-lib#8]
Part of the task requires understand, learning and writing Rust, and therefor this opens the door for reimplementing some core features and allow to verify them in another ways. This issue aims to track the development of adhoc technologies that can be redone in Rust in order to benefit from the language capabilities.
- [x] Implement r2pipe.rs (to use rust from inside or outside r2)
- [ ] Implement a3f in rust? (libr/core/p/core_a2f.c) - analysis engine written in rust based on evil
- [x] Implement ESIL parser and emulator
- [ ] Bindings for r2 APIs - valabind --rust

**Comment by XVilka** [comment]
Or even using rust to rewrite valabind, since vala is the *nix only, pain to compile in the windows world.

**Comment by radare** [comment]
vala works runs and builds fine on windows, i have been using it several years ago, and iirc there are builds of it in some repos. vala is still best option than rust for valabind imho.

**Comment by chinmaydd** [comment]
@radare is there any resource used to understand the a2f analysis engine? The source in libr/core/p/core_anal.c is highly undocumented.

**Comment by radare** [comment]
No docs out there, its documented in C. I think the a2f rewrite is way more clean and readable than af. Also, defragger is working on that a2f and did some goodies to it. Do you have any specific question? Maybe irc is a good place to ask this.

Also, this is the radeco repo, not r2 one

**Comment by chinmaydd** [comment]
@radare I see. The radeco-lib issue specifies a task to implement the same in Rust so I was wondering if I could work on it. I could not quite find the documentation for it in the r2 source. As for posting it on IRC, I did ask the doubt but no one responded for quite a while.

I will try to look into the a2f source again.

**Comment by radare** [comment]
i think @defragger is actually doing this, for fun, not to integrate it within radeco, but it will be cool if you two work together in a separate repo (or maybe radare2-extras).

**Comment by XVilka** [comment]
Closing this, as unrelated and partially finished. Please open new bugs if you need something particular.
